### ISSUE TITLE
可以丢个demo出来看看？

### ISSUE THREAD

**Issue by xmyxm** [qiqiboy/react-animated-router#2]
问题一：路由在跳转下一个页面的时候会导致，下一个页面的组件渲染两份出来（以完成这个滑动动画），但问题是渲染两次会导致组件的生命周期执行两次有不必要的消耗。。。方便有demo丢出来看看？

问题二：在ios app 的uiwebview环境下这个页面的过渡动画失效了

**Comment by qiqiboy** [comment]
已在实际业务中应用：https://www.itiger.com/mi/

**Comment by xmyxm** [comment]
访问了你的页面，华为手机自带浏览器动画也是失效了，其它浏览器正常

**Comment by qiqiboy** [comment]
我遇到过部分手机上动画失效的情况，这种情况猜测是对react-transition-group的cssTransition实现不兼容。同样实现原理的ng-animate vue-animate都一样失效。mi.com小米的网站也有动画，你可以看看是不是也一样会失效

**Comment by xmyxm** [comment]
动画效果都不理想，我用chrome的performance分析了下，发现华为js性能太差消耗极大，动画和过程中，js最好异步延迟执行

**Comment by changfu2015** [comment]
进入页面的时候怎么上个页面有退出的动画，下个页面没有进入的动画

**Comment by changfu2015** [comment]
![image](https://user-images.githubusercontent.com/14310202/50409478-ffd1c980-082d-11e9-8269-958c15b10ece.png)
这是我的页面结构

![image](https://user-images.githubusercontent.com/14310202/50409485-0f511280-082e-11e9-8566-5e788b657ed8.png)
发现你的有两个
